

name: Build Executables

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install and Build
        run: |
          curl https://pyenv.run | bash
          echo $SHELL
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install
          pip install pyinstaller
          pyinstaller --name example_ubuntu_18_04 -F example.py
          ls
          ./dist/example_ubuntu_18_04

  build_macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - name: Install and Build
        run: |
          brew install pyenv
          echo $SHELL
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install
          pip install pyinstaller
          pyinstaller --name example_macos_11 -F example.py
          ls
          ./dist/example_macos_11



  build_windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2

      - name: Install and Build
        run: |
          choco install pyenv-win
          echo $SHELL
          env PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install
          pip install pyinstaller
          pyinstaller --name example_windows_server_2022 -F example.py
          ls
          ./dist/example_windows_server_2022


